# Generated by Django 5.1.3 on 2024-11-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.login_table')),
            ],
        ),
    ]
