# Generated by Django 5.1.3 on 2024-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_registration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_table',
            name='First_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration_table',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration_table',
            name='PhoneNo',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='registration_table',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration_table',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
