# Generated by Django 5.1.3 on 2024-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_alter_blockchain_transaction_table_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain_transaction_table',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
