# Generated by Django 5.1.3 on 2024-12-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_complaint_table_feedback_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_table',
            old_name='First_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='registration_table',
            old_name='Last_name',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='registration_table',
            name='PhoneNo',
        ),
        migrations.RemoveField(
            model_name='registration_table',
            name='date_of_birth',
        ),
    ]
