# Generated by Django 5.1 on 2025-01-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_complaint_table_complaint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_hash', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
