# Generated by Django 5.1 on 2025-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0012_transaction_remove_donation_charity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_address',
            new_name='sender_address',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
